name: docs
on:
  push:
    branches: master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Build docs
        run: npm run docs
      - name: Build playground
        run: npm run build
        working-directory: packages/playground
        env:
          PLAYGROUND_BASE_PATH: /bvh/playground/
      - run: mkdir docs/playground && cp -r packages/playground/dist/* docs/playground
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
